[build]
  publish = "."

[[headers]]
  for = "/app-ads.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "max-age=3600"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "max-age=86400"

[[headers]]
  for = "/*.md"
  [headers.values]
  Cache-Control = "no-cache, no-store, must-revalidate"
  Pragma = "no-cache"
  Expires = "0"

[[redirects]]
  from = "/privacy"
  to = "/POLITICA_PRIVACIDAD.md"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/TERMINOS_SERVICIO.md"
  status = 200

[[redirects]]
  from = "/support"
  to = "/support.html"
  status = 200
